### PR TITLE
[ImgBot] Optimize image

### PR DESCRIPTION
**Pull request by cooljeanius**
[ImgBot](https://imgbot.net/docs/) reduces image file sizes losslessly with [ImageMagick](https://imagemagick.org/index.php), [Svgo](https://github.com/svg/svgo), and [MozJpeg](https://github.com/mozilla/mozjpeg). Here is its result for this repository:

/readme-settings-pane.png -- 146.04kb -> 122.47kb (16.14%)

### CODE REVIEW

**Comment by cooljeanius** [comment]
@darwin time to archive this repo?

**Comment by darwin** [comment]
@cooljeanius I don't archive repos. I don't see value in that. I guess people can see last activity on the repo.

**Comment by cooljeanius** [comment]
Well, archiving repos can help save people from spending time opening a PR against something that the owner no longer maintains...

**Comment by cooljeanius** [comment]
Anyways, never mind...

**Pull request closed without merging**
